pipeline:

  frontend:
    image: node:10
    commands:
      - npm install
      - npm run generate

  lint:
    image: node:10
    commands:
      - npm run lint

  deploy_review:
    image: drillster/drone-rsync
    secrets: [ rsync_key, rsync_user ]
    hosts:
      - ci.core.uconn.edu
    source: ./dist/*
    target: ~/squaredlabs-${DRONE_BUILD_NUMBER}
    delete: true
    script:
      - TARGET_PATH=~/squaredlabs-${DRONE_BUILD_NUMBER}
      - DEPLOY_PATH=/srv/nginx/pages/ci/squaredlabs/${DRONE_BRANCH}/public
      - mkdir -p $DEPLOY_PATH
      - rsync -az --delete $TARGET_PATH/* $DEPLOY_PATH
      - rm -rf $TARGET_PATH

  deploy_prod:
    image: drillster/drone-rsync
    secrets: [ rsync_key, rsync_user ]
    hosts:
      - squaredlabs.uconn.edu
    source: ./dist/*
    target: ~/squaredlabs-${DRONE_BUILD_NUMBER}
    delete: true
    when:
      branch:
        - master
    script:
      - TARGET_PATH=~/squaredlabs-${DRONE_BUILD_NUMBER}
      - DEPLOY_PATH=/var/www/squaredlabs
      - rsync -az --delete $TARGET_PATH/* $DEPLOY_PATH
      - rm -rf $TARGET_PATH
