version: "3"
services:
    web:
        build: ./
        container_name: squaredlabs-nuxt
        environment:
            - HOST=0.0.0.0
        ports:
            - 3000:3000
    mysql:
        image: mysql:5.6
        container_name: squaredlabs-mysql
        environment:
            MYSQL_DATABASE: "squaredlab"
            MYSQL_ROOT_PASSWORD: "directus"
            MYSQL_USER: "directus"
            MYSQL_PASSWORD: "password"
        volumes:
            - ./docker/mysql:/var/lib/mysql
    directus:
        image: getdirectus/directus:6.4
        container_name: squaredlabs-directus-api
        depends_on:
            - mysql
        volumes:
            - ./docker/directus/storage:/var/www/html/storage
        environment:
            MYSQL_USER: "directus"
            MYSQL_PASSWORD: "password"
            MYSQL_ENV_MYSQL_DATABASE: "squaredlab"
            MYSQL_PORT_3306_TCP_ADDR: "mysql"
            MYSQL_PORT_3306_TCP_PORT: "3306"
            MYSQL_ENV_MYSQL_PASSWORD: "password"
            MYSQL_ENV_MYSQL_USER: "directus"
        ports:
            - 8081:8080


